### ISSUE TITLE
JSON encoding should handle unions

### ISSUE THREAD

**Issue by jmckaskill** [jmckaskill/go-capnproto#12]
Unions are only handled for struct union members. We should fix it so it handles all cases and also switch to using a switch statement.

**Comment by DanielMorsing** [comment]
Unions can only exist as members inside structs according to the capn proto specification.

I'll look into generating a switch statement instead of the current if statement mess.

**Comment by jmckaskill** [comment]
Ah true. I misread the code and thought the discriminant check was around the struct as a whole and not the struct member.
