### ISSUE TITLE
setting a value to a List(struct)

### ISSUE THREAD

**Issue by cwndrws** [jmckaskill/go-capnproto#20]
Not sure if this would be better on the main Cap'n Proto discussion, but I'll try here. How does one set a pointer in a list? I have a struct that looks like:

```
struct Map {
        map @0 :List(Item);
        struct Item {
                name @0 :Text;
                value :union {
                        int @1 :Int32;
                        string @2 :Text;
                        map @3 :Map;
                }
        }
}
```

I can create a Map. Then I create a MapItemList with the segment from the Map and the length that I want, and I set the MapItemList to the Map using SetMap(). I then use that segment to start creating MapItems, but I don't know how to set the pointers to my newly created MapItem's to their indexes in the MapItemList. If I print out the resulting bytes, I can see the data is there, but I can't get the data out of the list using the provided read functions, likely because I am not setting pointers to the data in the list. Here is the function I'm messing around with: 

```
func WriteMap(mm map[string]interface{}) bytes.Buffer {
        ns := capn.NewBuffer(nil)
        m := NewRootMap(ns)
        mil := NewMapItemList(ns, len(mm))
        m.SetMap(mil)
        counter := 0
        for k, v := range mm {
                mi := NewMapItem(ns)
                mi.SetName(k)
                switch v.(type) {
                case string:
                        mi.Value().SetString(v.(string))
                case int:
                        mi.Value().SetInt(int32(v.(int)))
                default:
                        panic("OH SNAP")
                }
                counter++
        }
        buf := bytes.Buffer{}
        ns.WriteTo(&buf)
        return buf
}
```

Anyone see what I'm doing wrong? Or how I can do this?

**Comment by c00w** [comment]
I cast to capnp.PointerList and used Set(index, object)

**Comment by cwndrws** [comment]
I tried that, and got an 'index out of range' panic, but I will have to
investigate source, as to where that panic is coming from.

-Charlie
